# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 8  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  # l: [1.00, 1.00, 512]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
# YOLOv8.0n backbone

backbone:
  # [from, repeats, module, args]
  - [-1, 1, InputData, [3, 96, 96, 192]]  # input data dim
  - [0, 1, List_Split, [1]] # added 1/8  1 
  - [0, 1, List_Split, [2]] # added 1/16  2
  - [0, 1, List_Split, [3]] # added 1/32   3                  
  - [0, 1, List_Split, [0]] # img                   

  - [-1, 1, Conv, [64, 3, 2]]  # 5-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 6-P2/4
  - [-1, 2, C2f, [128, True]] #7
  - [-1, 1, Conv, [256, 3, 2]]  # 8-P3/8
  - [-1, 5, C2f_DCNV3, [256, True]] #9
  - [-1, 1, Conv, [512, 3, 2]]  # 10-P4/16
  - [-1, 5, C2f_DCNV3, [512, True]] #11
  - [-1, 1, Conv, [1024, 3, 2]]  # 12-P5/32
  - [-1, 3, C2f_DCNV3, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 14

# YOLOv8.0n head
head:
  - [-1, 1, DySample, [2]] #1/32->1/16    15
  - [[-1, 11], 1, Concat, [1]]  #1/16                         16
  - [-1, 3, C2f, [512]]  #1/16                                17

  - [-1, 1, DySample, [2]] #1/16->1/8       20
  - [[-1, 9, 1], 1, MSTFv1, [1, "conv3d", 0.25]]  # 1/8                           21
  - [-1, 3, C2f, [256]]  #1/8                                   22

  - [-1, 1, Conv, [256, 3, 2]]  #1/8->1/16                      23
  - [[-1, 17, 2], 1, MSTFv1, [1, "conv3d", 0.25]]  #1/16                           24
  - [-1, 3, C2f, [512]]  #1/16                                  25

  - [-1, 1, Conv, [512, 3, 2]]  #1/16->1/32                    26
  - [[-1, 14, 3], 1, MSTFv1, [1, "conv3d", 0.25]]  #1/32
  - [-1, 3, C2f, [1024]]  #1/32                                 28

  - [[20, 23, 26], 1, Detect, [nc]]  # Detect(P3, P4, P5) 20