# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 8  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  # l: [1.00, 1.00, 512]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
# YOLOv8.0n backbone

backbone:
  # [from, repeats, module, args]
  - [-1, 1, InputData, [3,[128, 256, 512]]]  # input data dim
  - [0, 1, List_Split, [1]] # added data                      
  - [0, 1, List_Split, [0]] # img                   

  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 2, C2f, [128, True]] #2
  - [-1, 1, Conv, [256, 3, 2]]  #5-P3/8
  - [-1, 5, C2f, [256, True]] #4
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 5, C2f, [512, True]] #6
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 12

# YOLOv8.0n head
head:
  - [[1, 7, 9, 12], 1, MSTF_BLOCK, []] # depth, width  13

  - [13, 1, List_Split, [0]] #1/4                             14
  - [13, 1, List_Split, [1]] #1/8                            15
  - [13, 1, List_Split, [2]] #1/16                            16

  - [12, 1, nn.Upsample, [None, 2, 'nearest']] #1/32->1/16    17
  - [[-1, 15], 1, Concat, [1]]  #1/16                         18
  - [-1, 3, C2f, [512]]  #1/16                                19

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/16->1/8       20
  - [[-1, 14], 1, Concat, [1]]  # 1/8                           21
  - [-1, 3, C2f, [256]]  #1/8                                   22

  - [-1, 1, Conv, [256, 3, 2]]  #1/8->1/16                      23
  - [[-1, 19], 1, Concat, [1]]  #1/16                           24
  - [-1, 3, C2f, [512]]  #1/16                                  25

  - [-1, 1, Conv, [512, 3, 2]]  #1/16->1/32                    26
  - [[-1, 16], 1, Concat, [1]]  #1/32
  - [-1, 3, C2f, [1024]]  #1/32                                 28

  - [[22, 25, 28], 1, Detect, [nc]]  # Detect(P3, P4, P5) 20