# Ultralytics YOLO 🚀, AGPL-3.0 license
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
# YOLO
datasampler:  #使得生成的index和视频关联
datasetname: YOLODataset #YOLODataset YOLOVideoDataset YOLOStreamDataset
# YOLOFT
# datasampler: streamSampler #使得生成的index和视频关联
# datasetname: YOLOVideoDataset #YOLODataset YOLOVideoDataset YOLOStreamDataset
split_mode: length #random all  表示视频切片策略 length时严格按照长度切片， random表示按照长度附近进行波动切片

# train:gaode_5 test:gaode_6
train: [/data/jiahaoguo/dataset/gaode_6/annotations/yolo/gaode_6_rm198_exclude14569.txt, /data/jiahaoguo/dataset/gaode_all/gaode_5/annotations/yolo/gaode_5.txt]
train_labels_dir: [/data/jiahaoguo/dataset/gaode_6/annotations/yolo/, /data/jiahaoguo/dataset/gaode_all/gaode_5/annotations/yolo/]
train_images_dir: [/data/jiahaoguo/dataset/gaode_6/images/, /data/jiahaoguo/dataset/gaode_all/gaode_5/images/]

val: /data/jiahaoguo/dataset/gaode_6/annotations/task1/task1_test.txt
val_labels_dir: /data/jiahaoguo/dataset/gaode_6/annotations/yolo/
val_images_dir: /data/jiahaoguo/dataset/gaode_6/images/

test: /data/jiahaoguo/dataset/gaode_6/annotations/task1/task1_test.txt
test_labels_dir: /data/jiahaoguo/dataset/gaode_6/annotations/yolo/
test_images_dir: /data/jiahaoguo/dataset/gaode_6/images/

split_length: [1] #先使用10的片段训练，再50 "all"表示不切割 #{2:12, 3:8, 4:6, 5:5, 6:4}

split_batch_dict:
  1: 34
  2: 15 #s1
  3: 8
  4: 6
  5: 5
  6: 4
  8: 7

match_number: 1  #当前帧前后各取一共几个关连帧，match_number=2即前后各取一个
interval: 4    # 取得帧间隔当前帧
interval_mode: interval #all：interval也会取尽所有视频 single则all/interval数量

#coco eval
eval_ann_json: /data/jiahaoguo/dataset/gaode_6/annotations/task1/task1_test.json
classes_map: [0,1]
# Classes
names:
  0: static
  1: moving